### ISSUE TITLE
4 years without any actions - maybe makes sense already to withdraw this proposal?

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-promise-try#13]

**Comment by ljharb** [comment]
Time isn’t a factor.

**Comment by zloirock** [comment]
Time **is** a factor. The situation with `.at` is an example.

**Comment by ljharb** [comment]
That had nothing to do with time. The original proposal was inadequate; the new proposal is more suited to the language.

If a proposal arrives which makes more sense than this one to solve its problems, this one will be replaced by it; until then, whether it take me years or decades, i still hope to advance this one.

**Comment by zloirock** [comment]
So if you hope to advance this one - why don't you do anything for this for a long time?

**Comment by ljharb** [comment]
Because I’m merely human, and my list of priorities is long. When i both have time and it is appropriate to do so, i will again seek advancement.

Since stage 1 is merely a problem TC39 wishes to explore further, it should have no impact on anyone to keep this proposal active (except perhaps those that wish it to advance sooner, for whom withdrawing it would not serve either).

**Comment by ljharb** [comment]
The proposal achieved stage 2 today at TC39. → #15
